import { useAtom } from 'jotai';
import { languageAtom } from '../../atoms';

const Strings={
	'en-US':{
		about: 'About',
		aboutText: 'Palmyra-Építő Kft. was founded in Budapest, and we are dedicated to providing the highest quality construction services to our clients. Our mission is to make your dreams come true, whether it\'s house building or apartment renovation, and our vision is to become a key player in the Hungarian construction industry, continuously providing innovative and sustainable solutions to our clients.',
		after: 'After:',
		apartments: 'Apartments',
		before: 'Before:',
		construction: 'Residential and non-residential building construction',
		constructionDescription: 'Comprehensive service from planning to implementation, including office buildings and shops.',
		consultation: 'Technical consultation',
		consultationDescription: 'Expert advice at every stage of construction, Technical inspection and Responsible technical management.',
		contact: 'Contact',
		contactDetails: 'Contact details',
		contactPageTitle: 'Contact us',
		cookiePolicy:'Cookie policy',
		followUs: 'Follow us:',
		heroTextSubtitle: 'General contracting from design to handover',
		heroTextTitle: 'We bring your vision to life',
		houseConstruction: 'Family house construction',
		houseConstructionDescription: 'Crafting your dream family home with personalized care and attention to every detail.',
		learnMore: 'Learn more',
		legal: 'Legal',
		locale:'EN/HU',
		message: 'Message',
		pageNotFound: 'Page not found',
		projectNotFound: 'Project not found!',
		projects: 'Projects',
		projectsInfo:{
			barbershopDescription: '',
			barbershopName: 'Barbershop',
			barbershopType:'Barbershop',
			midoDescription: '',
			midoName: 'Restaurant',
			midoType:'Restaurant',
		},
		renovation: 'Apartment renovation',
		renovationDescription: 'Complete apartment renovation projects, including interior design work.',
		restaurant: 'Restaurant',
		send: 'Send',
		services: 'Services',
		yourEmail: 'Your email address',
		yourName: 'Your name',
	},
	'hu-HU': {
		about: 'Rólunk',
		aboutText: 'A Palmyra-Építő Kft. Budapesten alakult, és elkötelezetten dolgozunk azon, hogy a legjobb minőségű építőipari szolgáltatásokat nyújtsuk ügyfeleinknek. Küldetésünk, hogy álmait valóra váltsuk, legyen szó házépítésről vagy lakásfelújításról, és víziónk, hogy a magyar építőipar meghatározó szereplőjévé váljunk, folyamatosan innovatív és fenntartható megoldásokkal szolgálva ügyfeleinket.',
		after: 'Utána:',
		apartments: 'Lakások',
		before: 'Előtte:',
		construction: 'Lakó- és nem lakó Épület építése',
		constructionDescription: 'Teljes körű szolgáltatás a tervezéstől a kivitelezésig, beleértve irodaházakat, üzleteket is.',
		consultation:'Műszaki tanácsadás',
		consultationDescription: 'Szakértői tanácsadás az építkezés minden fázisában, Műszaki ellenőrzés és Felelős műszaki vezetés.',
		contact: 'Kapcsolat',
		contactDetails: 'Elérhetőségek',
		contactPageTitle: 'Lépjen kapcsolatba velünk',
		cookiePolicy:'Süti tájékoztató',
		followUs: 'Kövessen minket:',
		heroTextSubtitle: 'Generál kivitelezés tervezéstől kulcsátadásig',
		heroTextTitle: 'Megvalósítjuk ötleteit',
		houseConstruction: 'Családiház építés',
		houseConstructionDescription: 'Egyedi és kulcsrakész családi házak építése.',
		learnMore: 'Tudjon meg többet',
		legal:'Jogi',
		locale:'EN/HU',
		message: 'Üzenet',
		pageNotFound: 'Az oldal nem található.',
		projectNotFound: 'A projekt nem található!',
		projects: 'Projektek',
		projectsInfo:{
			barbershopDescription: '',
			barbershopName: 'Barbershop',
			barbershopType:'Barbershop',
			midoDescription: '',
			midoName: 'Étterem',
			midoType:'Étterem',
		},
		renovation: 'Lakásfelújítás',
		renovationDescription: 'Teljes lakásfelújítási projektek, beleértve a belsőépítészeti munkákat is.',
		restaurant: 'Étterem',
		send: 'Küldés',
		services: 'Szolgáltatások',
		yourEmail: 'Az ön email címe',
		yourName: 'Az ön neve',
	}
};
Object.freeze(Strings);
function translate(value,section){
	const [language,] = useAtom(languageAtom);
	const result = section? Strings[language][section][value]:  Strings[language][value];
	return result??value;
}
export default translate;