import { useAtom } from 'jotai';
import { languageAtom } from '../../atoms';

const Strings={
	'en-US':{
		about: 'About',
		aboutText: 'We\'re Palmyra-Építő Kft., a general contracting firm in Budapest. We take on house builds, apartment renovations, and commercial projects, and see each one through from the first plans to handover. Clear scope, realistic timelines, and work we stand behind.',
		after: 'After:',
		apartments: 'Apartments',
		baAfter: 'After',
		baBefore: 'Before',
		backHome: 'Back to home',
		before: 'Before:',
		beforeAfterTitle: 'Before / After',
		statsAria: 'Our track record in numbers',
		statYears: 'Years in business',
		statProjects: 'Projects completed',
		statArea: 'Built & renovated',
		statCities: 'Cities & towns',
		storyEyebrow: 'Transformation',
		storyTitle: 'Before & after',
		storyHint: 'Drag to compare',
		timelineEyebrow: 'Process',
		timelineTitle: 'Step by step',
		galleryEyebrow: 'Details',
		galleryTitle: 'The finished space',
		metaDuration: 'Duration',
		metaLocation: 'Location',
		metaScope: 'Type',
		metaYear: 'Year',
		quoteCtaText: 'Tell us what you have in mind and we\'ll get in touch to talk it through.',
		quoteCtaTitle: 'Want a project like this?',
		quoteEmailSubject: 'Quote request',
		relatedProjects: 'More projects',
		callUs: 'Call us',
		catAll: 'All',
		catCommercial: 'Commercial',
		catRenovation: 'Renovation',
		catResidential: 'Residential',
		construction: 'Residential & commercial construction',
		constructionDescription: 'Full builds from planning to handover, including offices, shops, and other commercial spaces.',
		consultation: 'Technical consultation',
		consultationDescription: 'Expert guidance at every stage of a build — technical inspection and responsible technical management.',
		processTitle: 'How every project works',
		processStep1Title: 'Site survey',
		processStep1Desc: 'We listen to your needs and assess the site together.',
		processStep2Title: 'Planning',
		processStep2Desc: 'We prepare detailed plans and a transparent quote.',
		processStep3Title: 'Build',
		processStep3Desc: 'We deliver on time, on budget, and to the highest standard.',
		processStep4Title: 'Handover',
		processStep4Desc: 'You receive a finished result with full documentation.',
		constructionHighlight1: 'Office & retail fit-out',
		constructionHighlight2: 'Structural & civil works',
		constructionHighlight3: 'Design-to-build delivery',
		renovationHighlight1: 'Full strip-out and rebuild',
		renovationHighlight2: 'Interior design included',
		renovationHighlight3: 'Plumbing, electrical & finishes',
		houseHighlight1: 'Custom architectural plans',
		houseHighlight2: 'Turnkey family home',
		houseHighlight3: 'Energy-efficient construction',
		consultationHighlight1: 'On-site technical inspection',
		consultationHighlight2: 'Responsible technical management',
		consultationHighlight3: 'Independent expert advice',
		contact: 'Contact',
		contactDetails: 'Contact details',
		contactPageTitle: 'Contact us',
		contactPrompt: 'Tell us about your project and we\'ll get back to you shortly.',
		cookiePolicy:'Cookie policy',
		emailUs: 'Email us',
		followUs: 'Follow us:',
		heroTextSubtitle: 'General contracting from design to handover',
		heroTextTitle: 'We build your vision',
		houseConstruction: 'Family house construction',
		houseConstructionDescription: 'Custom family homes, built turnkey down to the last detail.',
		learnMore: 'Learn more',
		legal: 'Legal',
		locale:'EN/HU',
		message: 'Message',
		noProjectsInCategory: 'No projects in this category yet.',
		pageNotFound: 'Page not found',
		projectNotFound: 'Project not found',
		projects: 'Projects',
		projectsInfo:{
			barbershopDescription: 'A full renovation that turned an empty unit into a sleek, modern barbershop — including a new mezzanine level.',
			barbershopName: 'Barbershop',
			barbershopType:'Barbershop',
			midoDescription: 'A full renovation of a food venue into a modern restaurant — a new dining area, a fresh street-front, and the washrooms.',
			midoName: 'Restaurant',
			midoType:'Restaurant',
			counterCaption: 'The service counter',
			diningCaption: 'The dining area',
			washroomCaption: 'The washroom',
			storefrontCaption: 'The street front',
			kitchenCaption: 'The kitchen',
			stageEmptyCaption: 'The empty unit',
			stageStructureCaption: 'Structure & ceiling',
			stagePlasterCaption: 'Plastering & new stairs',
			stageSurfacesCaption: 'Floors & finished stairs',
			stageDoneCaption: 'The finished salon',
		},
		renovation: 'Apartment renovation',
		renovationDescription: 'Complete apartment renovations, including the interior design.',
		restaurant: 'Restaurant',
		send: 'Send',
		services: 'Services',
		viewAllProjects: 'View all projects',
		yourEmail: 'Your email address',
		yourName: 'Your name',
	},
	'hu-HU': {
		about: 'Rólunk',
		aboutText: 'A Palmyra-Építő Kft. budapesti generálkivitelező cég. Házépítést, lakásfelújítást és üzleti beruházásokat vállalunk, és mindegyiket az első tervektől a kulcsrakész átadásig visszük végig. Átlátható feltételek, tartható határidők, és munka, amit utána is felvállalunk.',
		after: 'Utána:',
		apartments: 'Lakások',
		baAfter: 'Utána',
		baBefore: 'Előtte',
		backHome: 'Vissza a főoldalra',
		beforeAfterTitle: 'Előtte / Utána',
		statsAria: 'Eredményeink számokban',
		statYears: 'Éve a piacon',
		statProjects: 'Befejezett projekt',
		statArea: 'Megépítve és felújítva',
		statCities: 'Város és település',
		storyEyebrow: 'Átalakítás',
		storyTitle: 'Előtte és utána',
		storyHint: 'Húzza az összehasonlításhoz',
		timelineEyebrow: 'Folyamat',
		timelineTitle: 'Lépésről lépésre',
		galleryEyebrow: 'Részletek',
		galleryTitle: 'Az elkészült tér',
		metaDuration: 'Időtartam',
		metaLocation: 'Helyszín',
		metaScope: 'Típus',
		metaYear: 'Év',
		quoteCtaText: 'Mesélje el, mit tervez, és hamarosan jelentkezünk, hogy átbeszéljük.',
		quoteCtaTitle: 'Hasonló projektre vágyik?',
		quoteEmailSubject: 'Ajánlatkérés',
		relatedProjects: 'További projektek',
		before: 'Előtte:',
		callUs: 'Hívjon minket',
		catAll: 'Összes',
		catCommercial: 'Üzleti',
		catRenovation: 'Felújítás',
		catResidential: 'Lakó',
		construction: 'Lakó- és üzleti épületek építése',
		constructionDescription: 'Teljes körű kivitelezés a tervezéstől az átadásig, irodák és üzlethelyiségek építését is vállaljuk.',
		consultation:'Műszaki tanácsadás',
		consultationDescription: 'Szakértői tanácsadás az építkezés minden szakaszában — műszaki ellenőrzés és felelős műszaki vezetés.',
		processTitle: 'Hogyan zajlik egy projekt',
		processStep1Title: 'Helyszíni felmérés',
		processStep1Desc: 'Meghallgatjuk igényeit, és közösen felmérjük a helyszínt.',
		processStep2Title: 'Tervezés',
		processStep2Desc: 'Részletes terveket és átlátható árajánlatot készítünk.',
		processStep3Title: 'Kivitelezés',
		processStep3Desc: 'Határidőre, a megbeszélt kereten belül, a legjobb minőségben dolgozunk.',
		processStep4Title: 'Átadás',
		processStep4Desc: 'Teljes dokumentációval, készen adjuk át a munkát.',
		constructionHighlight1: 'Iroda- és üzlethelyiség kialakítás',
		constructionHighlight2: 'Szerkezeti és mélyépítési munkák',
		constructionHighlight3: 'Tervezéstől a kivitelezésig',
		renovationHighlight1: 'Teljes bontás és újraépítés',
		renovationHighlight2: 'Belsőépítészeti tervezéssel együtt',
		renovationHighlight3: 'Gépészet, villany és burkolat',
		houseHighlight1: 'Egyedi építészeti tervek',
		houseHighlight2: 'Kulcsrakész családi ház',
		houseHighlight3: 'Energiahatékony kivitelezés',
		consultationHighlight1: 'Helyszíni műszaki ellenőrzés',
		consultationHighlight2: 'Felelős műszaki vezetés',
		consultationHighlight3: 'Független szakértői tanácsadás',
		contact: 'Kapcsolat',
		contactDetails: 'Elérhetőségek',
		contactPageTitle: 'Lépjen kapcsolatba velünk',
		contactPrompt: 'Meséljen a projektjéről, és hamarosan jelentkezünk.',
		cookiePolicy:'Süti tájékoztató',
		emailUs: 'Írjon nekünk',
		followUs: 'Kövessen minket:',
		heroTextSubtitle: 'Generálkivitelezés a tervezéstől a kulcsrakész átadásig',
		heroTextTitle: 'Megvalósítjuk az elképzeléseit',
		houseConstruction: 'Családi ház építése',
		houseConstructionDescription: 'Egyedi családi házak kulcsrakész kivitelezése, az utolsó részletig.',
		learnMore: 'Tudjon meg többet',
		legal:'Jogi',
		locale:'EN/HU',
		message: 'Üzenet',
		noProjectsInCategory: 'Ebben a kategóriában még nincs projekt.',
		pageNotFound: 'Az oldal nem található.',
		projectNotFound: 'A projekt nem található.',
		projects: 'Projektek',
		projectsInfo:{
			barbershopDescription: 'Egy üres helyiség teljes felújítása stílusos, modern borbélyüzletté — új galériaszinttel.',
			barbershopName: 'Barbershop',
			barbershopType:'Barbershop',
			midoDescription: 'Egy vendéglátóhely teljes felújítása modern étteremmé — új étkezőtér, megújult utcai front és mosdók.',
			midoName: 'Étterem',
			midoType:'Étterem',
			counterCaption: 'A kiszolgálópult',
			diningCaption: 'Az étkezőtér',
			washroomCaption: 'A mosdó',
			storefrontCaption: 'Az utcai front',
			kitchenCaption: 'A konyha',
			stageEmptyCaption: 'Az induló állapot',
			stageStructureCaption: 'Szerkezet és mennyezet',
			stagePlasterCaption: 'Vakolás, új lépcső',
			stageSurfacesCaption: 'Burkolatok, kész lépcső',
			stageDoneCaption: 'A kész szalon',
		},
		renovation: 'Lakásfelújítás',
		renovationDescription: 'Teljes lakásfelújítás, a belsőépítészeti munkákkal együtt.',
		restaurant: 'Étterem',
		send: 'Küldés',
		services: 'Szolgáltatások',
		viewAllProjects: 'Összes projekt megtekintése',
		yourEmail: 'Az Ön e-mail címe',
		yourName: 'Az Ön neve',
	}
};
Object.freeze(Strings);
function useTranslate(){
	const [language,] = useAtom(languageAtom);
	return (value,section)=>{
		const result = section? Strings[language][section][value]:  Strings[language][value];
		return result??value;
	};
}
export default useTranslate;